# Generated by Django 4.2.7 on 2023-11-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now=True)),
                ('nacionality', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('answer_1', models.CharField(max_length=1024, null=True)),
                ('answer_2', models.CharField(max_length=1024, null=True)),
                ('answer_3', models.CharField(max_length=1024, null=True)),
                ('answer_4', models.CharField(max_length=1024, null=True)),
                ('evsi', models.CharField(max_length=255)),
                ('svsn', models.CharField(max_length=255)),
                ('tvsf', models.CharField(max_length=255)),
                ('jvsp', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
            ],
        ),
    ]
