# Generated by Django 4.2.7 on 2023-11-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0004_question_alter_user_answer_1_alter_user_answer_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answer_1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answer_2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answer_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='answer_4',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mbti.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mbti.user')),
            ],
        ),
    ]
