# Generated by Django 4.2.7 on 2023-11-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0006_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', error_messages={'required': 'Error'}, max_length=50),
        ),
    ]
