# Generated by Django 4.2.7 on 2023-11-24 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0007_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', error_messages={'required': 'Error'}, max_length=50, validators=[django.core.validators.MinLengthValidator(20, 'Error min')]),
        ),
    ]
