# Generated by Django 4.2.7 on 2023-11-24 18:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0009_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', max_length=50, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
    ]
