# Generated by Django 4.2.7 on 2023-11-24 18:39

import app_mbti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0010_alter_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(default='', validators=[app_mbti.models.NumWordsValidator(20)]),
        ),
    ]
