# Generated by Django 4.2.7 on 2023-11-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0015_user_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=255)),
                ('index_title', models.CharField(max_length=255)),
                ('index_language', models.CharField(max_length=255)),
                ('index_name_placeholder', models.CharField(max_length=255)),
                ('index_nacionality_placeholder', models.CharField(max_length=255)),
                ('index_email_placeholder', models.CharField(max_length=255)),
                ('index_start_button', models.CharField(max_length=255)),
                ('aceptar_title', models.CharField(max_length=255)),
                ('aceptar_paragraph', models.CharField(max_length=2048)),
                ('aceptar_terms', models.CharField(max_length=255)),
                ('aceptar_accept_button', models.CharField(max_length=255)),
                ('aceptar_last_button', models.CharField(max_length=255)),
                ('terminos_title', models.CharField(max_length=255)),
                ('terminos_paragraph', models.CharField(max_length=5000)),
                ('terminos_reject_button', models.CharField(max_length=255)),
                ('terminos_accept_button', models.CharField(max_length=255)),
                ('preguntas_title', models.CharField(max_length=255)),
                ('preguntas_paragraph', models.CharField(max_length=2048)),
                ('preguntas_answer_placeholder', models.CharField(max_length=255)),
                ('preguntas_microphone', models.CharField(max_length=255)),
                ('preguntas_last_button', models.CharField(max_length=255)),
                ('preguntas_next_button', models.CharField(max_length=255)),
                ('preguntas_finish_button', models.CharField(max_length=255)),
                ('resultado_title', models.CharField(max_length=255)),
                ('resultado_dichotomies', models.CharField(max_length=255)),
                ('resultado_result', models.CharField(max_length=255)),
                ('resultado_paragraph', models.CharField(max_length=2048)),
                ('resultado_report', models.CharField(max_length=255)),
                ('resultado_last_button', models.CharField(max_length=255)),
                ('resultado_next_button', models.CharField(max_length=255)),
                ('fin_title', models.CharField(max_length=255)),
                ('fin_thanks', models.CharField(max_length=255)),
                ('fin_name', models.CharField(max_length=255)),
                ('fin_last_button', models.CharField(max_length=255)),
            ],
        ),
    ]
