# Generated by Django 4.2.7 on 2023-11-30 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0016_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='preguntas_paragraph',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_title',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resultado_dichotomies',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resultado_result',
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_evsi_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_evsi_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_jvsp_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_jvsp_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_svsn_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_svsn_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_tvsf_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas_tvsf_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_extroversion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_introversion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_intuicion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_juicio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_pensamiento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_percepcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_sensacion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='resultado_sentimiento',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='language',
            name='aceptar_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='resultado_paragraph',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='language',
            name='terminos_paragraph',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='LanguageResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mbti.language')),
            ],
        ),
    ]
