# Generated by Django 4.2.7 on 2023-11-30 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0017_remove_language_preguntas_paragraph_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='fin_name',
        ),
        migrations.RemoveField(
            model_name='language',
            name='resultado_paragraph',
        ),
    ]
