# Generated by Django 4.2.7 on 2023-11-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0018_remove_language_fin_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='language',
            name='preguntas_evsi_paragraph',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_evsi_title',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_jvsp_paragraph',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_jvsp_title',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_svsn_paragraph',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_svsn_title',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_tvsf_paragraph',
        ),
        migrations.RemoveField(
            model_name='language',
            name='preguntas_tvsf_title',
        ),
        migrations.AddField(
            model_name='language',
            name='preguntas',
            field=models.ManyToManyField(null=True, to='app_mbti.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
