# Generated by Django 4.2.7 on 2023-11-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0019_remove_language_preguntas_evsi_paragraph_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(),
        ),
    ]
