# Generated by Django 4.2.7 on 2023-12-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mbti', '0021_languageresult_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('sp', 'Español'), ('en', 'Inglés')], default='sp', max_length=255),
        ),
    ]
